[project]
name = "ee40098-coursework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.7",
    "pywavelets>=1.9.0",
    "scikit-learn>=1.7.2",
    "scipy>=1.16.3",
    "tensorflow>=2.20.0",
]
